### ISSUE TITLE
Sir this is un urgent please help mehow to solf this error

### ISSUE THREAD

**Issue by lxamir** [opensource-socialnetwork/opensource-socialnetwork#1280]
Stack trace:
#0 /home/allindia/public_html/ossn/classes/OssnDatabase.php(181): OssnDatabase->execute()
#1 /home/allindia/public_html/ossn/classes/OssnSite.php(35): OssnDatabase->select(Array, true)
#2 /home/allindia/public_html/ossn/libraries/ossn.lib.system.php(29): OssnSite->getAllSettings()
#3 /home/allindia/public_html/ossn/system/start.php(36): include_once('/home/allindia/...')
#4 /home/allindia/public_html/ossn/index.php(11): require_once('/home/allindia/...')
#5 {main}
  thrown in /home/allindia/public_html/ossn/classes/OssnDatabase.php on line 78

**Comment by lxamir** [comment]
kindly anyone help me

**Comment by lxamir** [comment]
kindly pleaassseee???????????

**Comment by lianglee** [comment]
You'll need to provide complete error,  the error above missing the main information.
