### ISSUE TITLE
"Unknown column" bug due to double quote use in MySQL 8

### ISSUE THREAD

**Issue by johndmulhausen** [opensource-socialnetwork/opensource-socialnetwork#1500]
```
[27-Aug-2019 21:03:36 America/Chicago] OssnDatabaseException: Unknown column 'admin' in 'where clause' 
 SELECT  u.guid, u.* FROM ossn_users as u  WHERE(u.time_created IS NOT NULL AND u.type = "admin")  ORDER by u.guid ASC LIMIT 0, 10;  in /var/www/html/classes/OssnDatabase.php:96
Stack trace:
#0 /var/www/html/classes/OssnDatabase.php(195): OssnDatabase->execute()
#1 /var/www/html/classes/OssnUser.php(700): OssnDatabase->select(Array, true)
#2 /var/www/html/components/Kernel/ossn_com.php(21): OssnUser->searchUsers(Array)
#3 /var/www/html/components/Kernel/ossn_com.php(76): ossn_kernal_is_established()
#4 /var/www/html/classes/OssnComponents.php(170): include_once('/var/www/html/c...')
#5 /var/www/html/libraries/ossn.lib.components.php(69): OssnComponents->loadComs()
#6 /var/www/html/system/start.php(35): include_once('/var/www/html/l...')
#7 /var/www/html/index.php(12): require_once('/var/www/html/s...')
#8 {main}
```

PHP Version 7.2.19-0ubuntu0.18.04.2
MySQL: Running on DigitalOcean's MySQL 8 managed database product

Changing `"admin"` to `'admin'` in the query makes it work. Go figure. Probably happening all over the place. So, I fixed this by searching for:

```
"admin"'
```

And changing it to:

```
\'admin\''
```

Do that across the whole codebase and this error goes away

**Comment by lianglee** [comment]
Works fine with MySQL 8

**Comment by suprematis** [comment]
I followed this link and was able to find the fix [](https://www.digitalocean.com/community/questions/sql-requests-with-double-quotes-not-working-with-managed-database).  No need to rename all instances of 'admin' on the whole codebase.
