### ISSUE TITLE
[B] Passed variable is not an array or object in classes\OssnUser.php:1053 

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1633]
InvalidArgumentException: Passed variable is not an array or object in classes\OssnUser.php:1053 Stack trace: #0 classes\OssnUser.php(1053): ArrayIterator->__construct(false) #1 system\plugins\default\pages\administrator\contents\dashboard.php(15): OssnUser->getGenders() #2 libraries\ossn.lib.views.php(27): include('C:\\Bserver\\htdo...') #3 libraries\ossn.lib.views.php(50): ossn_include('C:/Bserver/htdo...', Array) #4 libraries\ossn.lib.plugins.php(75): ossn_view('C:/Bserver/htdo...', Array) #5 libraries\ossn.lib.admin.php(204): ossn_plugin_view('pages/administr...') #6 libraries\ossn.lib.page.php(67): ossn_administrator_pagehandler(Array, 'administrator') #7 index.php(22): ossn_load_page('administrator', Array) #8 {main}

**Comment by lianglee** [comment]
Steps to reproduce , 
1. Login into admin account. (without deleting session/logout).
2. Remove old database and install new version, once database is initialized without adding new account visit admin URL (by mistake) and this issue appears.

I believe non-blocking issue, going to close it.
