### ISSUE TITLE
Error 500 Site is crashing 

### ISSUE THREAD

**Issue by ulanded001** [opensource-socialnetwork/opensource-socialnetwork#1857]
After leaving the session open on background the whole site crashes and need to leave it for an hour or so to be able to refresh and login again.
This is happening on the free version, and gave me a GULP! moment,, don't know what to do ! need help !

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at your hosting provider to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by ulanded001** [comment]
how do I bring it back to live ?

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error
follow case B (download standalone tool to find issue)

I don't think issue is with session , many providers limit number of
requests per hour the hosting account can make and after hour those
resources reset.

Check server logs also from hosting panel

**Comment by ulanded001** [comment]
Dear Arsalan,, 
I have contacted the tech people from the server, and make a ticket of service according to your explanation.
the point for me is that in the same server I have the landing page and crm. they are not affected. only OSSN .

On the Error Logs , I saw a user who tried several times,, I guess he got no success to login again.
Will Keep you posted with the response from the server guys.

The only details I am having is that I get OK and login to the site ,  go to Administraor  console, and just  at the next click , wherever I do it , it crashes with the error 500. 

The same very same happens if you log in  from a mobile device . 

this is the site URL : https://ulanded.com/Social_uLanded/
if you add the main one as https://ulanded.com/Social_uLanded/index.php  then it comes alive again, but if you go https://ulanded.com/Social_uLanded/home  it crashes

**Comment by ulanded001** [comment]
Have also enabled the error reporting as instructed on "B".... will keep follow up. Cache is disabled now

**Comment by ulanded001** [comment]
GOt an error log .. here it goes ... yes deffinitely is a OSSN issue .. 
Pasting some lines from the error log.. couldnt find a place where to upload it as file......


[23-Jan-2021 22:55:39 America/Mexico_City] PHP WARNING: 2021-01-23 22:55:39 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[23-Jan-2021 22:55:50 America/Mexico_City] PHP WARNING: 2021-01-23 22:55:50 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[23-Jan-2021 22:56:20 America/Mexico_City] PHP WARNING: 2021-01-23 22:56:20 (CST): "in_array() expects parameter 2 to be array, bool given" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php (line 212)
[23-Jan-2021 22:56:56 America/Mexico_City] PHP WARNING: 2021-01-23 22:56:56 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[23-Jan-2021 23:22:24 America/Mexico_City] PHP WARNING: 2021-01-23 23:22:24 (CST): "exif_read_data(phpWZ6CO7): File not supported" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnFile.php (line 452)
[23-Jan-2021 23:23:19 America/Mexico_City] PHP WARNING: 2021-01-23 23:23:19 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[23-Jan-2021 23:24:30 America/Mexico_City] Com Installer Error: Former component is still in place
[24-Jan-2021 00:09:02 America/Mexico_City] PHP WARNING: 2021-01-24 00:09:02 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[26-Jan-2021 23:22:49 America/Mexico_City] PHP WARNING: 2021-01-26 23:22:49 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[26-Jan-2021 23:25:13 America/Mexico_City] PHP WARNING: 2021-01-26 23:25:13 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[29-Jan-2021 15:47:01 America/Mexico_City] PHP WARNING: 2021-01-29 15:47:01 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:47:11 America/Mexico_City] PHP WARNING: 2021-01-29 15:47:11 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:47:29 America/Mexico_City] PHP WARNING: 2021-01-29 15:47:29 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:49:39 America/Mexico_City] PHP WARNING: 2021-01-29 15:49:39 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:51:09 America/Mexico_City] PHP WARNING: 2021-01-29 15:51:09 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:51:59 America/Mexico_City] PHP WARNING: 2021-01-29 15:51:59 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:51:59 America/Mexico_City] PHP WARNING: 2021-01-29 15:51:59 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:52:18 America/Mexico_City] PHP WARNING: 2021-01-29 15:52:18 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:54:35 America/Mexico_City] PHP WARNING: 2021-01-29 15:54:35 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:57:16 America/Mexico_City] PHP WARNING: 2021-01-29 15:57:16 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[29-Jan-2021 15:57:17 America/Mexico_City] PHP WARNING: 2021-01-29 15:57:17 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[01-Feb-2021 18:09:51 America/Mexico_City] PHP WARNING: 2021-02-01 18:09:51 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[01-Feb-2021 20:54:29 America/Mexico_City] PHP WARNING: 2021-02-01 20:54:29 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[01-Feb-2021 20:59:49 America/Mexico_City] PHP WARNING: 2021-02-01 20:59:49 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[01-Feb-2021 21:07:55 America/Mexico_City] PHP WARNING: 2021-02-01 21:07:55 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[01-Feb-2021 21:08:36 America/Mexico_City] PHP WARNING: 2021-02-01 21:08:36 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[01-Feb-2021 21:14:09 America/Mexico_City] PHP WARNING: 2021-02-01 21:14:09 (CST): "Creating default object from empty value" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnMessageTyping/classes/MessageTyping.php (line 57)
[01-Feb-2021 21:14:14 America/Mexico_City] PHP WARNING: 2021-02-01 21:14:14 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[02-Feb-2021 17:21:55 America/Mexico_City] PHP WARNING: 2021-02-02 17:21:55 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[02-Feb-2021 17:22:03 America/Mexico_City] PHP WARNING: 2021-02-02 17:22:03 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[03-Feb-2021 21:33:42 Europe/London] [#1612388022|0EC1F0E0441FAEF3FFB01BBA878B0E92] Error: Call to a member function canModerate() on bool in /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnWall/plugins/default/wall/siteactivity.php:17
Stack trace:
#0 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.views.php(27): include()
#1 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.views.php(50): ossn_include('/home/sites/14b...', Array)
#2 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.plugins.php(75): ossn_view('/home/sites/14b...', Array)
#3 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view('wall/siteactivi...')
#4 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.views.php(27): include('/home/sites/14b...')
#5 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.views.php(50): ossn_include('/home/sites/14b...', Array)
#6 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.plugins.php(75): ossn_view('/home/sites/14b...', Array)
#7 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.initialize.php(121): ossn_plugin_view('wall/pages/wall')
#8 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.page.php(73): ossn_user_pagehandler(Array, 'home')
#9 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/index.php(22): ossn_load_page('home', Array)
#10 {main}
[05-Feb-2021 16:44:40 America/Mexico_City] PHP WARNING: 2021-02-05 16:44:40 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[05-Feb-2021 16:48:19 America/Mexico_City] PHP WARNING: 2021-02-05 16:48:19 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[05-Feb-2021 16:48:47 America/Mexico_City] PHP WARNING: 2021-02-05 16:48:47 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[05-Feb-2021 16:50:04 America/Mexico_City] PHP WARNING: 2021-02-05 16:50:04 (CST): "exif_read_data(phpAvBti0): File not supported" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnFile.php (line 452)
[05-Feb-2021 16:50:40 America/Mexico_City] PHP WARNING: 2021-02-05 16:50:40 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[05-Feb-2021 16:53:50 America/Mexico_City] PHP WARNING: 2021-02-05 16:53:50 (CST): "exif_read_data(php7NS9B1): File not supported" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnFile.php (line 452)
[05-Feb-2021 16:57:51 America/Mexico_City] PHP WARNING: 2021-02-05 16:57:51 (CST): "in_array() expects parameter 2 to be array, bool given" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php (line 212)
[05-Feb-2021 16:58:30 America/Mexico_City] PHP WARNING: 2021-02-05 16:58:30 (CST): "in_array() expects parameter 2 to be array, bool given" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php (line 212)
[05-Feb-2021 17:05:19 America/Mexico_City] PHP WARNING: 2021-02-05 17:05:19 (CST): "in_array() expects parameter 2 to be array, bool given" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php (line 212)
[05-Feb-2021 17:07:44 America/Mexico_City] PHP WARNING: 2021-02-05 17:07:44 (CST): "exif_read_data(phpbrDwHI): File not supported" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnFile.php (line 452)
[05-Feb-2021 17:11:44 America/Mexico_City] PHP WARNING: 2021-02-05 17:11:44 (CST): "exif_read_data(phplGQUwR): File not supported" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnFile.php (line 452)
[09-Feb-2021 17:20:23 America/Mexico_City] PHP WARNING: 2021-02-09 17:20:23 (CST): "file_get_contents(https://api.github.com/repos/opensource-socialnetwork/opensource-socialnetwork/contents/opensource-socialnetwork.xml): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
" in file /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php (line 847)
[11-Feb-2021 19:30:11 Europe/London] PHP Deprecated:  Required parameter $params follows optional parameter $template in /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.views.php on line 264
[11-Feb-2021 19:30:14 Europe/London] [#1613071814|00F84BD92C9A74217248FEB41750C215] ArgumentCountError: Too few arguments to function _ossn_php_error_handler(), 4 passed and exactly 5 expected in /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php:805
Stack trace:
#0 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php(255): _ossn_php_error_handler(2, 'Undefined prope...', '/home/sites/14b...', 255)
#1 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnUser.php(200): OssnEntities->get_entities()
#2 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.users.php(113): OssnUser->getUser()
#3 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.users.php(34): ossn_user_by_guid(1)
#4 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php(258): ossn_users('ossn', 'init', NULL)
#5 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/system/start.php(42): ossn_trigger_callback('ossn', 'init')
#6 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/index.php(12): require_once('/home/sites/14b...')
#7 {main}
[11-Feb-2021 19:30:17 Europe/London] [#1613071817|00F84BD92C9A74217248FEB41750C215] ArgumentCountError: Too few arguments to function _ossn_php_error_handler(), 4 passed and exactly 5 expected in /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php:805
Stack trace:
#0 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php(255): _ossn_php_error_handler(2, 'Undefined prope...', '/home/sites/14b...', 255)
#1 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnUser.php(200): OssnEntities->get_entities()
#2 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.users.php(113): OssnUser->getUser()
#3 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.users.php(34): ossn_user_by_guid(1)
#4 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php(258): ossn_users('ossn', 'init', NULL)
#5 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/system/start.php(42): ossn_trigger_callback('ossn', 'init')
#6 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/index.php(12): require_once('/home/sites/14b...')
#7 {main}
[11-Feb-2021 19:30:22 Europe/London] [#1613071822|00F84BD92C9A74217248FEB41750C215] ArgumentCountError: Too few arguments to function _ossn_php_error_handler(), 4 passed and exactly 5 expected in /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php:805
Stack trace:
#0 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnEntities.php(255): _ossn_php_error_handler(2, 'Undefined prope...', '/home/sites/14b...', 255)
#1 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/classes/OssnUser.php(200): OssnEntities->get_entities()
#2 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.users.php(113): OssnUser->getUser()
#3 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.users.php(34): ossn_user_by_guid(1)
#4 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/libraries/ossn.lib.system.php(258): ossn_users('ossn', 'init', NULL)
#5 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/system/start.php(42): ossn_trigger_callback('ossn', 'init')
#6 /home/sites/14b/1/115eed749e/public_html/Social_uLanded/index.php(12): require_once('/home/sites/14b...')
#7 {main}

**Comment by lianglee** [comment]
The issue seems with your provider their IP reached the limit to access API from github (for new version checking).  You can ignore this. Rest issue is that the files system is trying to check (which user uploaded) not found
