### ISSUE TITLE
OSSN Website Error on Index

### ISSUE THREAD

**Issue by tshpr** [opensource-socialnetwork/opensource-socialnetwork#1981]
Hello guys,

Not sure if this is the right place to report this, but I couldn't figure a way to do it on the website, so I will open issue here. One of my friends is facing an error with his OSSN install. I have redacted some data.

The website itself says: System error. Please try again later. You can send an email with the details to an administrator at websiteemail@email.com

This is a copy of the most recent errors on the error log. 

#6 {main}
[02-Aug-2021 08:18:00 America/Detroit] Error: Length must be greater than 0 in /home/cpanelusername/public_html/rockbook/libraries/ossn.lib.system.php:764
Stack trace:
#0 /home/cpanelusername/public_html/rockbook/libraries/ossn.lib.system.php(764): openssl_random_pseudo_bytes(0)
#1 /home/cpanelusername/public_html/rockbook/libraries/ossn.lib.initialize.php(201): ossn_string_decrypt('&\xFA\xABG\x89\xF9T\xBA', 'ossnossnossnoss...')
#2 /home/cpanelusername/public_html/rockbook/libraries/ossn.lib.initialize.php(63): ossn_pow_lnk_args()
#3 /home/cpanelusername/public_html/rockbook/libraries/ossn.lib.system.php(258): ossn_initialize('ossn', 'init', NULL)
#4 /home/cpanelusername/public_html/rockbook/system/start.php(39): ossn_trigger_callback('ossn', 'init')
#5 /home/cpanelusername/public_html/rockbook/index.php(12): require_once('/home/cpanelusername/...')
#6 {main}

We are running PHP 7.4.21 and OSSN version 5.2 as per the opensource-socialnetwork.xml file. As the website is not working, I am unable to retrieve any more details about the version.

It used to work, but I am not sure what changed to break it.

    <version>5.2</version>
    <stable_version>5.2</stable_version>
    <release>1577836800</release>
    <build>feb27461c56ae6768637aebfb08611f5954e6706</build>
    
    Let me know if you require more details.

**Comment by lianglee** [comment]
Yes its makes sense OSSN 5.2 is too old to run on php 7.x. Use php 7.0 or
upgrade to OSSN 5.6
