### ISSUE TITLE
A system error has occurred. Try again later.

### ISSUE THREAD

**Issue by janiorolim** [opensource-socialnetwork/opensource-socialnetwork#2161]
(Sorry for any mistakes, this text has been translated!)

Everything was working very well, until out of nowhere it disfigured the entire site and started to display the following message:

A system error has occurred. Try again later. You can email the details of this error to the system administrator janiorolim5@gmail.com.

Error: Call to a member function iconURL() on bool in /home/vol2_6/epizy.com/epiz_31870354/htdocs/components/OssnProfile/plugins/default/profile/wall/profile/photo.php:18
Stack trace:
#0 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.views.php(27): include()
#1 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.views.php(50): ossn_include('/home/vol2_6/ep...', Array)
#2 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.plugins.php(75): ossn_view('/home/vol2_6/ep...', Array)
#3 /home/vol2_6/epizy.com/epiz_31870354/htdocs/components/OssnProfile/ossn_com.php(506): ossn_plugin_view('profile/wall/pr...', Array)
#4 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.system.php(223): ossn_wall_profile_photo('wall:template', 'profile:photo', NULL, Array)
#5 /home/vol2_6/epizy.com/epiz_31870354/htdocs/components/OssnWall/ossn_com.php(486): ossn_call_hook('wall:template', 'profile:photo', Array)
#6 /home/vol2_6/epizy.com/epiz_31870354/htdocs/components/OssnWall/plugins/default/wall/siteactivity.php(54): ossn_wall_view_template(Array)
#7 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.views.php(27): include('/home/vol2_6/ep...')
#8 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.views.php(50): ossn_include('/home/vol2_6/ep...', Array)
#9 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.plugins.php(75): ossn_view('/home/vol2_6/ep...', Array)
#10 /home/vol2_6/epizy.com/epiz_31870354/htdocs/components/OssnWall/plugins/default/wall/pages/wall.php(27): ossn_plugin_view('wall/siteactivi...')
#11 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.views.php(27): include('/home/vol2_6/ep...')
#12 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.views.php(50): ossn_include('/home/vol2_6/ep...', Array)
#13 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.plugins.php(75): ossn_view('/home/vol2_6/ep...', Array)
#14 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.initialize.php(121): ossn_plugin_view('wall/pages/wall')
#15 /home/vol2_6/epizy.com/epiz_31870354/htdocs/libraries/ossn.lib.page.php(79): ossn_user_pagehandler(Array, 'home')
#16 /home/vol2_6/epizy.com/epiz_31870354/htdocs/index.php(22): ossn_load_page('home', Array)
#17 {main}

![image](https://user-images.githubusercontent.com/95371442/171735625-90e69ce0-2e13-4daf-b1b3-1ab9558bbe9b.png)
![image](https://user-images.githubusercontent.com/95371442/171735696-3df2a03b-dc4e-4541-b2ef-01284a4a42c4.png)

**Comment by lianglee** [comment]
Did you modified the database? did you deleted some user manually from database?

**Comment by lianglee** [comment]
Closing as no response.
